In [6]:
import numpy as np

In [11]:
a_list = [1,2,3,4,5]
print(a_list)
b_list = [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]]
a_array = np.array(a_list)
b_array = np.array(b_list)
print(a_array)
print(b_array)
a_list

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[1, 2, 3, 4, 5]

In [12]:
a_array + 2

array([3, 4, 5, 6, 7])

In [34]:
print(b_array)
b_array.reshape(1,12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [17]:
c_array = np.array([9,9,9,9,9])
a_array * c_array

array([ 9, 18, 27, 36, 45])

In [26]:
d_array = np.array([[ 9,  9,  9,  9],
                    [ 9,  9,  9, 9],
                    [9, 9, 9, 9]])
b_array * d_array

array([[  9,  18,  27,  36],
       [ 45,  54,  63,  72],
       [ 81,  90,  99, 108]])

In [16]:
np.mean(a_array)

3.0

In [18]:
np.mean(b_array,0)

array([5., 6., 7., 8.])

In [20]:
e_array = np.array([-1,-2,-3,-4])
print(e_array)
np.abs(e_array)

[-1 -2 -3 -4]


array([1, 2, 3, 4])

In [21]:
'''
a_list = [1,2,3,4,5]
e_array = np.array([-1,-2,-3,-4])
'''
np.concatenate((a_array,e_array),axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [23]:
'''
b_list = [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]]

d_array = np.array([[ 9,  9,  9,  9],
                    [ 9,  9,  9, 9],
                    [9, 9, 9, 9]])
'''
np.concatenate((b_array,d_array),axis = 1)

array([[ 1,  2,  3,  4,  9,  9,  9,  9],
       [ 5,  6,  7,  8,  9,  9,  9,  9],
       [ 9, 10, 11, 12,  9,  9,  9,  9]])

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.ones(3)

array([1., 1., 1.])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.linspace(0,100,51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

In [72]:
'''
d_array = np.array([[ 9,  9,  9,  9],
                    [ 9,  9,  9, 9],
                    [9, 9, 9, 9]])
'''
np.dot(b_array,d_array)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [73]:
''''
b_list = [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]]
'''
f_array = np.array([[9,9,9],
                   [9,9,9],
                   [9,9,9],
                   [9,9,9]])
np.dot(b_array,f_array)

array([[ 90,  90,  90],
       [234, 234, 234],
       [378, 378, 378]])