In [38]:
import numpy as np

In [39]:
a = np.array([1,2,3,4,5])

In [40]:
a

array([1, 2, 3, 4, 5])

In [41]:
b = [1,2,3,4,5]

In [42]:
b

[1, 2, 3, 4, 5]

In [43]:
b+[6]

[1, 2, 3, 4, 5, 6]

In [44]:
a+6

array([ 7,  8,  9, 10, 11])

In [45]:
data = np.array([[10,50,50,0],[30,50,50,1],[40,10,50,4]])

In [46]:
data

array([[10, 50, 50,  0],
       [30, 50, 50,  1],
       [40, 10, 50,  4]])

In [33]:
data1 = np.array([[1,3,2,1],[3,5,5,2],[5,0,0,5]])

In [34]:
data1

array([[1, 3, 2, 1],
       [3, 5, 5, 2],
       [5, 0, 0, 5]])

In [54]:
5**2

25

In [55]:
data**data1

array([[       10,    125000,      2500,         0],
       [    27000, 312500000, 312500000,         1],
       [102400000,         1,         1,      1024]], dtype=int32)

In [32]:
10**11

100000000000

In [56]:
np.dot(data,data1)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [57]:
np.shape(data)

(3, 4)

In [59]:
data1 = data1.reshape(4,3)

In [61]:
data1

array([[1, 3, 2],
       [1, 3, 5],
       [5, 2, 5],
       [0, 0, 5]])

In [60]:
np.dot(data,data1)

array([[310, 280, 520],
       [330, 340, 565],
       [300, 250, 400]])